# Generated by Django 5.0.6 on 2024-05-25 15:45

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(blank=True, default='images/nophoto.jpeg', null=True, upload_to=utils.FileUpload.upload_to),
        ),
    ]
